HEIGHT_BASE = 45
WIDTH_BASE = 140
board = [[' ' for i in range(WIDTH_BASE)] for j in range(HEIGHT_BASE)]
filled = [['' for i in range(WIDTH_BASE)] for j in range(HEIGHT_BASE)]
filled2 = [['' for i in range(WIDTH_BASE)] for j in range(HEIGHT_BASE)]
colr = [[' ' for i in range(WIDTH_BASE)] for j in range(HEIGHT_BASE)]
ATTACKTIME = [100000000000]
ATTACK_DATA = []
CURRENT_LEVEL = 1
HEALTH_HUT = 0
HEALTH_TOWN = 500

SPEED_KING = 1
ATTACK_POWER_KING = 50
HEALTH_KING = 100

HEALTH_CANNON = 0
RANGE_CANNON = 6
ATTACK_POWER_CANNON = 15

HEALTH_WT = HEALTH_CANNON
RANGE_WT = RANGE_CANNON
ATTACK_POWER_WT = ATTACK_POWER_CANNON


HEALTH_BARB = 40
SPEED_BARB = 1
ATTACK_POWER_BARB = 10

HEALTH_ARC = HEALTH_BARB/2
SPEED_ARC = SPEED_BARB*2
ATTACK_POWER_ARC = ATTACK_POWER_BARB/2
RANGE_ARC = RANGE_CANNON+2

HEALTH_LOON = 500
SPEED_LOON = SPEED_BARB
ATTACK_POWER_LOON = 400
